### ISSUE TITLE
Not able to customize table cell width

### ISSUE THREAD

**Issue by amitraja4606** [henrybuilt/react-sticky-table#103]
Hello,
I have used react-sticky-table in my project since I had to fix my header and the first two columns.
But since my second column content is long and taking too much space I am not able to set its width even using inline style width and setting its attribute as important. For other columns, it is taking width according to header width. How can I customize its width?
![column width](https://user-images.githubusercontent.com/52194658/87903895-bfbee100-ca7a-11ea-87e2-58fcb777a5c0.JPG)

**Comment by amitraja4606** [comment]
code for reference. I have different form controls inside each cell on conditions. It will be very helpful If it resolves. 

import React, { Component } from 'react';
import { StickyTable, Row, Cell } from 'react-sticky-table';
import './Constraints.css'
const headers = [
	{ id: '#', label: '#', minWidCell: '40px' },
	{ id: 'Columns', label: 'Columns', minWidCell: '200px' },
	{ id: 'Required', label: 'Required', minWidCell: '50' },
	{ id: 'Data type', label: 'Data type', minWidCell: '130' },
	{ id: 'Precision', label: 'Precision', minWidCell: '100' },
	{ id: 'Ref Id', label: 'Ref Id', minWidCell: '200' },
	{ id: 'Allowed Values', label: 'Allowed Values', minWidCell: '230' },
	{ id: 'Unique', label: 'Unique', minWidCell: '100' },
	{ id: 'AndOR', label: 'AND/OR', minWidCell: '100' },
	{ id: 'Condition', label: 'Condition', minWidCell: '150' },
	{ id: 'DGW', label: 'DGW', minWidCell: '150' },
	{ id: 'Worksheet', label: 'Worksheet', minWidCell: '150' },
	{ id: 'Column', label: 'Column', minWidCell: '150' },
	{ id: 'Value', label: 'Value', minWidCell: '100' },
];

export default class ConstraintsStickyTable extends Component {
	constructor ( props ) {
		super( props );

	}

	render () {
		return (
			<div>
				<div style={ { width: '100%', height: '65vh', marginTop: '3%' } }>
					<StickyTable leftStickyColumnCount={2}>
						<Row>
							{ headers.map( ( header, idx ) => (
								<Cell
									key={ header.label }
									style={{width: header.minWidCell}}
									className={ header.label === 'Allowed Values' ? 'bg-primary text-white border- 
                                                                                            right' : 'bg-primary text-white' }
								>
									{ header.label }
								</Cell>
							) ) }
						</Row>
						{ this.props.columns.map( ( row, index ) => {
							return (
								<Row key={ Math.random() }>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ index + 1 }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8, width: '200px' } }>
										{ row.alias }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'isComplete' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'hasDataType' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'precision' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'ref_id' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } } className='border-right'>
										{ this.props.populateTableData( row, index, 'isContainedInArray' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'unique' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'andOr' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'condition' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'dgw' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'dataset' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'column' ) }
									</Cell>
									<Cell align={ 'left' } style={ { padding: 8 } }>
										{ this.props.populateTableData( row, index, 'value' ) }
									</Cell>
								</Row>
							);
						} ) }
					</StickyTable>
				</div>
			</div>
		);
	}
}

**Comment by amitraja4606** [comment]
One more thing, If I am selecting any form field the scroll is going to the bottom.

**Comment by maxhudson** [comment]
You can use `.sticky-table-cell:nth-child(2) { width: 100px }` or go like:

```jsx
<Cell>
  <div style={{maxWidth: '100px'}}>{2nd column content}

**Comment by amitraja4606** [comment]
Thanks @maxhudson . I tried the second one and it solved the width problem. One more thing to add, Since every table cell has form controls, the focus is lost from input field after typing a character and also selecting any form control here is scrolling the page to the bottom. How to handle that. I am adding code snippet for reference. Below is the code for required and ref_id columns.

populateTableData = ( data, idx, type ) => {
		switch ( type ) {
			case 'isComplete':
				return <input
					type="checkbox"
					id={ `blankCheckbox_required_${ Math.random() }` }
					checked={ this.findConstraintKey( data, 'isComplete' ) === true }
					onChange={ () => this.requiredFieldHandler( data, idx ) }
					aria-label="..."
					style={ { width: '20px', height: '20px' } } />;
	              case 'ref_id':
				let refId = this.getRefId( data, 'ref_id' );
				return <><input type="text"
					className="form-control form-control-sm"
					id={ `ref_id_${ idx }` }
					value={ this.findConstraintKey( data, 'ref_id' ) ? refId : '' }
					onChange={ ( event ) => this.refIdHandler( idx, event, data ) }
					placeholder=""
					disabled={ this.getSelectedDataType( data, 'hasDataType' ) || this.getSelectedDataType( data, 
                                                       'dateFormatValidation' ) }
				             ></input>
					{/* { this.state.refIdErrorIndex !== null &&
						this.state.refIdErrorIndex === idx && <span className='text-danger'>
							{ this.state.refIdErrorMessage }</span> } */}

				</>;
                             defaut: return;



methods;

	findConstraintKey = ( data, constraintType ) => {
		for ( let i = 0; i < data.constraints.length; i++ ) {
			if ( data.constraints[ i ].hasOwnProperty( constraintType ) ) {
				return true;
			}
		}
	};

handlers>>>>>>>

	refIdHandler = ( idx, event, data ) => {
		// event.persist();
		this.setState( { disableSaveAndCancel: false } );
		let value = event.target.value;
		if ( value.length < 5 ) {
			this.setState( { refIdErrorMessage: 'minimum length should be 5' } );
		} else {
			this.setState( { refIdErrorMessage: '' } );
		}
		this.setState( { refIdErrorIndex: idx }, () => {
			this.xyz( idx, value.trim(), data );
		} );

	};

	xyz ( idx, value, data ) {
		const { updateConstraints, columns } = this.props;
		const tempdata = [ ...columns ];
		let obj = { ref_id: { ext_id: '', rule_name: '' } };
		if ( data.constraints.length === 0 ) {
			obj.ref_id.ext_id = value;
			tempdata[ idx ].constraints.push( obj );
			updateConstraints( tempdata );
		} else {
			let isRefId = false;
			for ( let i = 0; i < data.constraints.length; i++ ) {
				if ( data.constraints[ i ].hasOwnProperty( 'ref_id' ) ) {
					isRefId = true;
					tempdata[ idx ].constraints[ i ].ref_id.ext_id = value;
					updateConstraints( tempdata );
					break;
				}
			}
			if ( !isRefId ) {
				obj.ref_id.ext_id = value;
				tempdata[ idx ].constraints.push( obj );
				updateConstraints( tempdata );
			}
		}

		if ( value === '' ) {
			for ( let i = 0; i < data.constraints.length; i++ ) {
				if ( data.constraints[ i ].hasOwnProperty( 'ref_id' ) ) {
					tempdata[ idx ].constraints.splice( i, 1 );
					updateConstraints( tempdata );
					break;
				}
			}
		}
	}

==============


	requiredFieldHandler = ( data, idx ) => {
		const { updateConstraints, columns } = this.props;
		const tempdata = [ ...columns ];
		let obj = { isComplete: { rule_name: '' } };
		this.setState( { disableSaveAndCancel: false } );

		if ( data.constraints.length === 0 ) {
			tempdata[ idx ].constraints.push( obj );
			updateConstraints( tempdata );
		} else {
			let isComplete = false;
			for ( let i = 0; i < data.constraints.length; i++ ) {
				if ( data.constraints[ i ].hasOwnProperty( 'isComplete' ) ) {
					isComplete = true;
					data.constraints.splice( i, 1 );
					tempdata[ idx ] = data;
					updateConstraints( tempdata );
					break;
				}
			}
			if ( !isComplete ) {
				tempdata[ idx ].constraints.push( obj );
				updateConstraints( tempdata );
			}
		}

	};

**Comment by maxhudson** [comment]
Are your inputs resizing as you type or something like that?

**Comment by amitraja4606** [comment]
No, Is it because of using form controls inside the table?

**Comment by maxhudson** [comment]
I'm not sure why that'd be an issue - I'll test an example out, but I would be surprised if it's an issue on our end

**Comment by amitraja4606** [comment]
Thanks for the update @maxhudson  Really appreciate your time and effort. It is a wonderful package that you created with minimum dependencies. Very easily configurable. I am also not able to figure out why the focus is lost.

**Comment by Stophface** [comment]
Any updates on this?
