### ISSUE TITLE
Remove `/docs` folder from NPM package

### ISSUE THREAD

**Issue by markerikson** [henrybuilt/react-sticky-table#105]
The `/docs` folder is being included in the published NPM package, including a bunch of prebuilt JS files and sourcemaps.  That makes the package multiple megabytes in size.

Please update the publishing process to _not_ include that folder - there's no reason for the published artifact to be that big given the size of the actual code.

**Comment by maxhudson** [comment]
This is what we published latest version with - did this a while ago, but forgot to comment!
```
npm notice 1.1kB  LICENSE      
npm notice 19.5kB dist/index.js
npm notice 41B    index.js     
npm notice 2.7kB  package.json 
npm notice 3.6kB  README.md
```
