### ISSUE TITLE
Can't apply styling to rows

### ISSUE THREAD

**Issue by ttiras** [henrybuilt/react-sticky-table#111]
It is not possible to apply styling to rows. How can i implement bg-color on hover?

**Comment by maxhudson** [comment]
@ttiras What's the CSS you're trying to use for the row? 

Generally you'd go: `.sticky-table-row:hover .sticky-table-cell { background-color: black }`

Hover styles on `display: table-row` are inconsistent in browsers

**Comment by ttiras** [comment]
> Hover styles on `display: table-row` are inconsistent in browsers

this is the knowledge i was looking for. 

thank you.

**Comment by manoadamro** [comment]
anyone know any other ways I can tell it I want `40px` cells?

<img width="333" alt="Screenshot 2021-05-05 at 16 19 09" src="https://user-images.githubusercontent.com/29605020/117165693-a0046980-adbd-11eb-9631-b939c06338ce.png">

<img width="216" alt="Screenshot 2021-05-05 at 16 20 39" src="https://user-images.githubusercontent.com/29605020/117165936-d641e900-adbd-11eb-8d3a-09d64bdfc11b.png">
