### ISSUE TITLE
Full width table

### ISSUE THREAD

**Issue by AthulNair** [henrybuilt/react-sticky-table#112]
Is it possible to make the table full width even if the no of columns are less. I am using this with bootstrap.

**Comment by maxhudson** [comment]
You can probably give your .stick-table-cell width: 100% or width: 33% etc

Css flex would be the most natural way to do this normally which you can
apply here if you’re fluent in it

**Comment by AthulNair** [comment]
.sticky-table-table{
    width: 100%;
}
This worked for me. Thanks @maxhudson

**Comment by maxhudson** [comment]
👍
