### ISSUE TITLE
Multiple Sticky Row

### ISSUE THREAD

**Issue by Joci933** [henrybuilt/react-sticky-table#12]
Hi,

How can I set multiple sticky row? I tried with stickyHeaderCount={4}, but it isn't working.

Thanks,

**Comment by maxhudson** [comment]
@Joci933 Unfortunately this isn't something that is functional yet - you can only use 0 or 1 for that value currently. It will be available soon though.

**Comment by maxhudson** [comment]
@Joci933 if you really need it, you're welcome to fork the project and try to implement it yourself. It should be fairly straightforward. You'd have to modify `getStickyRows()` and the row/column height calculation functions.

**Comment by Joci933** [comment]
`getStickyRows()`? Not `getStickyHeader()`?

**Comment by maxhudson** [comment]
@Joci933 sorry - yes `getStickyHeader()`

**Comment by micahd** [comment]
Just curious if the multiple headers is something you plan to implement?

**Comment by maxhudson** [comment]
@micahd yes it is

**Comment by maxhudson** [comment]
@Joci933 @micahd multiple headers/columns are now available

**Comment by micahd** [comment]
I was able to get version 2.0 up and running and it's working great with the multiple headers. Thanks!

**Comment by maxhudson** [comment]
@micahd that's great to hear!!
