### ISSUE TITLE
static rendering on server

### ISSUE THREAD

**Issue by mr2day** [henrybuilt/react-sticky-table#14]
I'm using react-sticky-table in a Gatsby project. At the building stage, when the site is statically rendered with "gatsby build" command, the process fails with error:

" WebpackError: navigator is not defined
  
  - index.js:198 new StickyTable
    ~/react-sticky-table/dist/index.js:198:1"

**Comment by maxhudson** [comment]
I'm not familiar with Gatsby or using React on the server. `navigator` is currently a necessary dependency used to detect firefox and avoid unusual behavior in it. It is a variable that isn't available as a global in node, it's provided by the browser. Sounds like a gatsby problem though - it should anticipate browser-defined globals. There may be a flag you can use to build it and ignore the undefined variable.
