### ISSUE TITLE
Sticky header getting overlapped by scrolling content

### ISSUE THREAD

**Issue by BrettStatman** [henrybuilt/react-sticky-table#18]
Hello,

I have a basic react-sticky-table setup with a fixed header. The sticky header keeps jumping behind the scrolling content:

<img width="795" alt="screen shot 2018-02-08 at 11 54 37 am" src="https://user-images.githubusercontent.com/4602425/35986532-4d35561e-0cc7-11e8-845a-d2df45d41eca.png">

The already applied z-index's seem to be getting ignored. A window resize fixes the issue. Any ideas on why this may be happening or a fix?

Note: appears to be in Chrome only, after scrolling the outer page.

Thank you.

**Comment by maxhudson** [comment]
@BrettStatman without seeing code or knowing what is different in your situation from the examples, it's hard to tell.

Some ideas:
- Try setting a background color on the cells if there isn't one already
- Try manually triggering a window resize event after the component is mounted
- Check the examples and make sure they're being followed precisely

**Comment by BrettStatman** [comment]
Tried those suggestions to no avail.

Here's the implementation:

Table Component:
```import React from 'react';
import { StickyTable, Row, Cell } from 'react-sticky-table';
import 'react-sticky-table/dist/react-sticky-table.css';

class Table extends React.Component {
  renderHeader() {
    const { columns } = this.props;
    const headerCells = columns.map(({ title, minWidth }) => (
      <Cell style={{ minWidth }}>{title}</Cell>
    ));

    return (
      <Row>
        {headerCells}
      </Row>
    );
  }

  renderRows() {
    const { data, columns } = this.props;
    const rows = [];

    // create a row for each data item
    for (let i = 0, numRows = data.length; i < numRows; i += 1) {
      const rowData = data[i];
      const cells = [];

      // create cells for each column in the row
      for (let j = 0, numColumns = columns.length; j < numColumns; j += 1) {
        const { key } = columns[j];
        const cellData = rowData[key];
        cells.push(<Cell>{cellData}</Cell>);
      }

      rows.push(<Row>{cells}</Row>);
    }

    return rows;
  }

  render() {
    return (
      <div style={{ width: '100%', height: '150px', background: '#FFFFFF' }}>
        <StickyTable stickyColumnCount={0}>
          {this.renderHeader()}
          {this.renderRows()}
        </StickyTable>
      </div>
    );
  }
}

export default Table;
```

---

Usage:

```
const data = [
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
  {
    name: 'Test Name',
    status: 'Test Status',
    something: 'Test Something',
    other: 'Other',
  },
];

const columns = [
  {
    title: 'Name',
    key: 'name',
    minWidth: 250,
  },
  {
    title: 'Status',
    key: 'status',
    minWidth: 225,
  },
  {
    title: 'Something',
    key: 'something',
    minWidth: 250,
  },
  {
    title: 'Other',
    key: 'other',
    minWidth: 100,
  },
];

<div style={{ width: 500 }}>
  <Table data={data} columns={columns} />
</div>
```

**Comment by maxhudson** [comment]
@BrettStatman Try setting a height on the wrapper div. Let me know if that does anything.

**Comment by BrettStatman** [comment]
Already have a height set on a wrapper around `<StickyTable>`. Added a height on the outermost div but same result.

**Comment by maxhudson** [comment]
@BrettStatman Ah yeah my bad. I'm not really sure. Maybe try triggering a window resize inside a setTimeout with a few hundred ms delay?

Luckily, since you only need a sticky header, there should be a number of other react component solutions people have made for that if you can't get this one to work.

**Comment by BrettStatman** [comment]
I do need to use the fixed column as well.

One major difference I noticed is that the parent that is scrolling outside of the table is a `flex` container. When that is no longer the case, the problem is fixed. Any ideas for getting this to work with a dynamic height flex parent?

**Comment by maxhudson** [comment]
@BrettStatman are you saying you need to be able to put the sticky table inside a container with `display: flex`? I haven't played around with that scenario, but if you've got it working without using flex, you can probably achieve the layout you're going for some other way. I understand that is not ideal...

One thing that might help is adding an additional wrapper that is display block and has a fixed height/width, and is a child of the `flex` cell element.

```
<div class="display-flex">
  <div class="display-flex-cell">
    <div class="display-block" width="100" height="100">
      <StickyTable/>
    </div>
  </div>
</div>
```

**Comment by maxhudson** [comment]
@BrettStatman Did you have any luck with this? v2 was just published it's possible it will fix your issue. Closing for now.

**Comment by BrettStatman** [comment]
@maxhudson - No wasn't able to get this working. Switched to a different solution for now!

**Comment by maxhudson** [comment]
@BrettStatman Ok - sorry about that. Out of curiosity, what are you using now? Maybe we can improve our solution if we see it.
