### ISSUE TITLE
scrollToCell function

### ISSUE THREAD

**Issue by oldo** [henrybuilt/react-sticky-table#21]
Hi there!

Nice component!

Is there a function for triggering a scroll to a particular cell in the table?

**Comment by maxhudson** [comment]
Not at the moment but that’s a good idea. Will add to the roadmap!

**Comment by maxhudson** [comment]
Happy to accept a PR if you end up implementing yourself. You may way to
consider generalizing a solution for both directions if you do implement :)

**Comment by oldo** [comment]
Thanks @maxhudson 

I'll see how I go and if I develop something will definitely create a PR. Cheers :-)

**Comment by maxhudson** [comment]
Not sure how this would work in a react-y way. Closing until there's action
