### ISSUE TITLE
Moving production of rows into separate file causes error

### ISSUE THREAD

**Issue by oldo** [henrybuilt/react-sticky-table#22]
Hi there :-)

Just getting my head around this component and have come across a little issue.

When I produce a table like so there is no problem:

```
const DaysTable = ({ dates, emptyFirst, hideTitle, rows, onClick }) => {
  return (
    <div style={{ width: '100%', height: '200px' }}>
      <StickyTable>
        <Row>
          {emptyFirst && <Cell />}
          {dates.map(day => <Cell key={day}>{moment(day).format(dayFormat)}</Cell>)}
        </Row>
      </StickyTable>
    </div>
  );
};
```

However I want to move the creation of the row into a separate file:

index.js
```
import TableHeader from './table-header';

const DaysTable = ({ dates, emptyFirst, hideTitle, rows, onClick }) => {
  return (
    <div style={{ width: '100%', height: '200px' }}>
      <StickyTable>
        <TableHeader dates={dates} emptyFirst={emptyFirst} />
      </StickyTable>
    </div>
  );
};
```

table-header.js
```
const DaysTableHeader = ({ dates, emptyFirst }) => {
  return (
    <Row>
      {emptyFirst && <Cell />}
      {dates.map(day => <Cell key={day}>{moment(day).format(dayFormat)}</Cell>)}
    </Row>
  );
};
```

However when I do so I get the error in console:
<img width="1108" alt="screen shot 2018-03-26 at 17 13 27" src="https://user-images.githubusercontent.com/4557648/37889617-08b79526-3119-11e8-8702-c35a097c51e5.png">

I'm not quite sure what I'm doing wrong here. This would usually work fine... Any thoughts?

**Comment by maxhudson** [comment]
@oldo it may be related to you not subclassing React.Component there. The specific error sounds like something unrelated. Also, I may be wrong, but making the `<Row>`'s children a `<Cell>` and an array of `<Cell>`s may not work as expected.

I think your goal of trying to move the row rendering out of the file is possible, but the approach may be the problem. I'd start with the simplest possible case of just exporting a class that renders an empty row with no props.

**Comment by maxhudson** [comment]
@oldo Any luck with this?

**Comment by oldo** [comment]
Hi @maxhudson 

No, actually I haven't really looked into it further because I realised that I can solve my particular problem (fixed first column) easily with CSS, so I've opted for that instead of another dependency in my project.

Feel free to close if you'd like. Thanks for following up though :-)

**Comment by maxhudson** [comment]
@oldo sounds good. Sticky header/column is usually much cleaner with just css. Lucky you!
