### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by oluckyman** [henrybuilt/react-sticky-table#3]
Seems like vertical scroll only works when dragging the sticky column. But when dragging the table itself there is no scroll in the table (the page scrolls instead). And without sticky column it’s impossible to scroll the table

**Comment by maxhudson** [comment]
Yeah I'm seeing the same thing you are. This is probably related to there being a table within a table. I'll look into it.

**Comment by maxhudson** [comment]
This may be a potentional solution: http://stackoverflow.com/questions/35469227/overflow-y-not-working-in-safari-inside-a-modal

`-webkit-overflow-scrolling: touch;`

**Comment by maxhudson** [comment]
This was indeed the solution. Mobile needs some work in general, but this specific issue is resolved in `v1.1.9`. Thank you for pointing it out.

https://henrybuilt.github.io/react-sticky-table/
