### ISSUE TITLE
Option to resize table cells to fill table width for small tables

### ISSUE THREAD

**Issue by jacobweber** [henrybuilt/react-sticky-table#31]
From the README:
> Responsive table dimensions (wrap it in any size container and it will fill that container)

Does this also apply to tables that are naturally smaller than the container, e.g. should it expand the column widths to fill the container? I'm not seeing this. For example, this table doesn't take up the full 600px:

```
import React from 'react';
import { StickyTable, Row, Cell } from 'react-sticky-table';
import 'react-sticky-table/dist/react-sticky-table.css';

export default class App extends React.Component {
	render() {
		return (
			<div style={{border: '1px solid red', width: '600px', height: '300px'}}>
				<StickyTable stickyHeaderCount={0} stickyColumnCount={0}>
					<Row>
						<Cell>A</Cell>
						<Cell>B</Cell>
						<Cell>C</Cell>
					</Row>
				</StickyTable>
			</div>
		);
	}
};
```

**Comment by amanesmedina** [comment]
Hi @jacobweber,

You can add `min-width: 100%;` to the class `.sticky-table-table`

**Comment by maxhudson** [comment]
Should be possible with css
