### ISSUE TITLE
Remove npm as dependency?

### ISSUE THREAD

**Issue by jabsatz** [henrybuilt/react-sticky-table#34]
I was wondering why npm it's not there as a devDep or even at all, I added this package to a project and it added like 100 extra deps because of that. I think it's really valuable to have a package with no deps at all.

**Comment by maxhudson** [comment]
@jabsatz that's definitely a mistake. Sorry about that. Will remove this weekend.

**Comment by maxhudson** [comment]
@jabsatz this is fixed in 2.0.4
