### ISSUE TITLE
Children cannot be connected to redux

### ISSUE THREAD

**Issue by michalpokojski** [henrybuilt/react-sticky-table#37]
If you import connected children, table does not render.
![image](https://user-images.githubusercontent.com/29205657/39359248-8feff1f0-4a19-11e8-9130-81a21d08d21e.png)

It seems like mandatory feature, and unfortunatelly i can't use it without it. Maybe on the weekend i'll work on fixing this issue.

**Comment by maxhudson** [comment]
@michalpokojski are you trying to connect to rows or cells? Unfortunately we have to destroy row elements and create new ones since the table is actually 4 separate tables (top left corner, header, column, and body)

**Comment by Rafi993** [comment]
It does seems to work thanks @maxhudson.It did cause some re-renders but it might be because of other issues too.

**Comment by maxhudson** [comment]
@Rafi993 great - if you confirm that superfluous render calls are an issue with the library, please open a separate issue!
