### ISSUE TITLE
Type Error: Super expression must either be null or function

### ISSUE THREAD

**Issue by danehildreth18** [henrybuilt/react-sticky-table#38]
Hey, not sure why this is happening, but I keep receiving the following error:

<img width="1046" alt="screen shot 2018-05-09 at 12 07 21 am" src="https://user-images.githubusercontent.com/25392225/39780593-d6eaead0-531d-11e8-8e69-2d23e4f97e1e.png">

Here is my code:
<img width="637" alt="screen shot 2018-05-09 at 12 08 57 am" src="https://user-images.githubusercontent.com/25392225/39780628-eda5c376-531d-11e8-88d9-5777115b72f2.png">

<img width="633" alt="screen shot 2018-05-09 at 12 09 16 am" src="https://user-images.githubusercontent.com/25392225/39780640-f88adca4-531d-11e8-9ba2-e86c4728dbb5.png">

My current react setup is simply the one I downloaded from here https://github.com/facebook/create-react-app.

Any ideas as to what is causing this issue? Really want to use this sticky table!

**Comment by danehildreth18** [comment]
Hi @maxhudson . When I add that to my index file, the console result is 'undefined.'

**Comment by danehildreth18** [comment]
And here is my package.json setup @maxhudson 

<img width="442" alt="screen shot 2018-05-09 at 12 27 43 am" src="https://user-images.githubusercontent.com/25392225/39781316-e4bb2d3a-531f-11e8-95f7-72caede5fdac.png">

**Comment by maxhudson** [comment]
@danehildreth18 I can't find any documentation on when `PureComponent` was added to `react`, but my guess is that it was introduced after `15.0.0`.

Bumping your `react` and `react-dom` versions to `16.0.0` in the package file and then reinstalling dependencies should fix for now. 

I don't think there's any reason we need to use a `PureComponent` - that was likely a mistake that needs to be fixed, but I won't be able to look into that for a few days.

**Comment by danehildreth18** [comment]
Thanks for your help @maxhudson !

**Comment by danehildreth18** [comment]
Also, just for anyone with the same issue, the solution offered by @maxhudson  worked: update to 16.0.0 for both react and react-dom. Even though the terminal will throw a warning saying that react-sticky-table requires 15.0.0 for both react and react-dom, it actually needs 16.0.0. The example code for react-sticky-table is working now!

**Comment by maxhudson** [comment]
@danehildreth18 great. I'll either update the requirement or drop `PureComponent`. Thanks!
