### ISSUE TITLE
Sticky Footer & Right Column

### ISSUE THREAD

**Issue by ValeraT1982** [henrybuilt/react-sticky-table#43]
Is it possible to have sticky rows at the bottom?

**Comment by maxhudson** [comment]
Unfortunately not at the moment, but that would be nice to have!

**Comment by maxhudson** [comment]
This is very straightforward to set up now. We'll put it on the fast track.

**Comment by youngbw** [comment]
How fast-tracked we talkin here?

**Comment by maxhudson** [comment]
apparently not very! Will take a look this week

**Comment by maxhudson** [comment]
https://github.com/henrybuilt/react-sticky-table/releases/tag/4.3.1

**Comment by maxhudson** [comment]
@youngbw https://henrybuilt.github.io/react-sticky-table/?path=/story/basic--sticky-on-all-sides

**Comment by youngbw** [comment]
Appreciate the quick turn around!
