### ISSUE TITLE
how to add horizontal scrollbar?

### ISSUE THREAD

**Issue by paulobdelacruz16** [henrybuilt/react-sticky-table#44]
how to show horizontal scrollbar? its not showing to me...

**Comment by paulobdelacruz16** [comment]
also we don't have any example of showing the horizontal scrollbar....

**Comment by maxhudson** [comment]
@paulobdelacruz16 the first example in the demo [here](https://henrybuilt.github.io/react-sticky-table/) has a horizontal scrollbar, but it may not appear for you. Can you share a screenshot of what you see when you scroll horizontally on that first example?

**Comment by paulobdelacruz16** [comment]
here:

**Comment by paulobdelacruz16** [comment]
i can't see any horizontal scrollbar. i think its browser issue..
i used Google Chrome version 52.0.2743.116

**Comment by paulobdelacruz16** [comment]
anyways thank u. i think i need to update my browser^^
