### ISSUE TITLE
jsfiddle or similar showcasing environment?

### ISSUE THREAD

**Issue by Jaguar1** [henrybuilt/react-sticky-table#49]
Hi,

Do you provide links to sources over a CDN? If not: please advise: is it possible to use showcasing environment like jsfiddle?

Best regards,
Vladimir

**Comment by Jaguar1** [comment]
Hi @maxhudson,

Thank you for your quick response. 
I tried links but not sure what's wrong: https://jsfiddle.net/ovtwm87x/
Could you please advice?

Best regards,
Vladimir

**Comment by maxhudson** [comment]
I'm not sure how to help unfortunately. I don't have experience with using React outside a node application. It looks like the package is unable to extract PureComponent from the React package for some reason. I don't know of anyone else who has used `react-sticky-table` like this either, unfortunately.

**Comment by Jaguar1** [comment]
Thank you anyway. If someone knows how to use it outside app please fix the fiddle. This could be useful for many developers.

**Comment by sibelius** [comment]
use can use https://docusaurus.io/ or storybook or docz for this
