### ISSUE TITLE
Is there a way to apply css to each row on hover or mouseenter?

### ISSUE THREAD

**Issue by cmhsu-cs** [henrybuilt/react-sticky-table#50]
Is there a way to style the Row element?

**Comment by maxhudson** [comment]
Yes - you can use css selectors (you can inspect elements to find out what their selectors are with your browser)

**Comment by ttiras** [comment]
this doesn't work for me on chrome. can't style rows. css applies to only cells. what i need is changing bg-color of row on hover. but i can't change the bg-color even without hover.

**Comment by maxhudson** [comment]
@ttiras What's the CSS you're trying to use for the row? 

Generally you'd go: `.sticky-table-row:hover .sticky-table-cell { background-color: black }`

Hover styles on `display: table-row` are inconsistent in browsers
