### ISSUE TITLE
The setColumnWidths method is not called when screen is shrinked

### ISSUE THREAD

**Issue by liujia214** [henrybuilt/react-sticky-table#51]
Hi,

I have a small sticky table with sticky header, and I give .sticky-table-table 100% to fill the container width.

When the screen width is growing, the setColumnWidths method is called to recalculate the column width, the new width and min-width are added to the column inline styles.

Then when we shrink the screen size back, the table size is not shrinked and a horizontal scroll bar is added. After I take a look at the source code, I found setColumnWidths is not called because the 'tableCellSizesChanged' is NOT true, and the reason is that the min-width in the column causes the 'bodyTable.offsetWidth' not decreasing even if its container width decreases. Below is the related code:

        ` var tableCellSizes = {
          corner: { width: this.dom.stickyCornerTable.offsetWidth, height: this.dom.stickyCornerTable.offsetHeight },
          header: { width: this.dom.stickyHeaderTable.offsetWidth, height: this.dom.stickyHeaderTable.offsetHeight },
          column: { width: this.dom.stickyColumnTable.offsetWidth, height: this.dom.stickyColumnTable.offsetHeight },
          body: { width: this.dom.bodyTable.offsetWidth, height: this.dom.bodyTable.offsetHeight }
        };

        var tableCellSizesChanged = JSON.stringify(tableCellSizes) !== JSON.stringify(this.oldTableCellSizes);

        var wrapperSizeChanged = JSON.stringify(wrapperSize) !== JSON.stringify(this.oldWrapperSize);

        if (forceCellTableResize || !this.oldTableCellSizes || tableCellSizesChanged) {
          this.setRowHeights();
          this.setColumnWidths();

          this.oldTableCellSizes = tableCellSizes;
        }`

I understand the min-width is to make the cell's width be dynamic, but how could we solve the shrink problem caused by it? Thanks

**Comment by maxhudson** [comment]
resolved in v3.0.1
