### ISSUE TITLE
Sizing of empty cells causes misalignment of cells in same row

### ISSUE THREAD

**Issue by StijnVh** [henrybuilt/react-sticky-table#52]
Suppose you create a table with 10 rows and 4 columns. When all 40 cells have content, then layout is fine. All 4 cells in each row do align (same height).

When however, some cells don't have content, layout is messed up. The height of the empty cells is different (less) than the height of other cells (at the same row). Wich causes all cells below (in the same column) to be shifted slightly upwards, causing misalignment of the 4 cells in the same row.

Example (with data blurred, but the issue should still be clear). The circle is drawn to point the empty cell,  having a smaller size than other cells in same row. Thus causing misalignment issue. 

![tableok](https://user-images.githubusercontent.com/15261086/49501533-62f5bf00-f873-11e8-858b-94fc3b2c8c24.png)

![tableskew](https://user-images.githubusercontent.com/15261086/49500996-31302880-f872-11e8-86c5-44fc76e019b3.png)

I've worked around this, by avoiding empty cells and if cell content would be empty instead add a <span> with a non-breaking space inside.

**Comment by maxhudson** [comment]
@StijnVh thanks for the heads up. This should be an easy fix. Hoping to do it myself, but if you want to make a PR, that would be more than welcome!

**Comment by maxhudson** [comment]
This should be fixed in v3.0.1
