### ISSUE TITLE
TypeError: "callback" argument must be a function

### ISSUE THREAD

**Issue by phuoctuong** [henrybuilt/react-sticky-table#54]
I cloned this project and try to run test but got a error at `setTimeout` function.
I guess the test is failed because of mount in enzyme. It's working when using shallow instead but I need to use mount function in my case.

Anyone help me to fix? Thanks in advance

**Comment by maxhudson** [comment]
Can you include the relevant portion of your test code? My guess is there are missing child components that are expected to be there (might need at least two rows and two columns?).

**Comment by phuoctuong** [comment]
I just cloned `react-sticky-table` project and run test on master branch as described in package-lock.json. As a result, the same error is thrown.

**Comment by maxhudson** [comment]
Should be fixed in 3.0.1
