### ISSUE TITLE
when console is open header scroll smoothly in x direction with the body but if i close the console-window header lags when i scroll in same direction :p.

### ISSUE THREAD

**Issue by akshayKanyan** [henrybuilt/react-sticky-table#57]
i dont know what is happening here.

maybe due to screen height or something or opening console accelrate css hardware.

when is scroll the body in x direction the header lag behind the body.

**Comment by maxhudson** [comment]
@akshayKanyan without being able to reproduce this myself this is pretty hard to fix. The table is not highly performant, so there is some slowness on some devices/browsers. If you can figure anything else out, or find a fix, please feel free to mention here to create a PR
