### ISSUE TITLE
horizontal scrollbar not showing in Safari

### ISSUE THREAD

**Issue by jrbarnid** [henrybuilt/react-sticky-table#59]
The horizontal scrollbar does not show in Safari. This can be seen using the demo.

**Comment by maxhudson** [comment]
Hi @jrbarnid - this should be fixed in v3.0.1, but I haven't updated the demo to match yet due to lack of time. Let me know if that works for you!

**Comment by jrbarnid** [comment]
The scrollbar works great in 3.0.1, thanks! I noticed my sticky column is no longer sticky, though? Is that part of the css that was removed?

**Comment by maxhudson** [comment]
How many sticky columns do you have? 
If it's just 1, it's a bug on my end that I'll try to fix today or tomorrow.
If more than 1, we don't support more than 1 yet with v3

**Comment by jrbarnid** [comment]
It's 1. Thanks for the info!

**Comment by maxhudson** [comment]
@jrbarnid Ok - probably an issue on our end. Are you explicitly specifying 1 sticky column to the react component?

**Comment by jrbarnid** [comment]
I've tried specifying 1 column and leaving as default, both had the same result (no sticky columns). I'm also specifying 0 for headers.

**Comment by maxhudson** [comment]
Ok thank you - will get back to you soon

**Comment by maxhudson** [comment]
@jrbarnid I looked into this and didn't see anything. Our demo is now updated to show that this does work. Can you provide your browser name and version?

Can you share the css properties of the cells that are supposed to be sticky? They should at least have `position: sticky` on them. Are you importing our stylesheet?

**Comment by maxhudson** [comment]
Closing this as it should be resolved now
