### ISSUE TITLE
headers reordering

### ISSUE THREAD

**Issue by vorlov** [henrybuilt/react-sticky-table#6]
if I pass a new array of headers with different order of header names it does not update width of sticky header Cells according to a new order of names

**Comment by maxhudson** [comment]
Can you be more specific and provide an example?

**Comment by vorlov** [comment]
ok, for example we have that code ```
<Row>
    { headers.map(header =>
      <Cell
        key={ header.key }
      >
        { header.name }
      </Cell>
    )}
</Row>
```
if we change the order of objects in headers array by a function call or setState, cells with id=sticky-header-cell-0 would change their content, but width will stay same based on prev content in the cell

**Comment by maxhudson** [comment]
@vorlov Interesting. I'll see if I can reproduce. Sounds like a bug.

**Comment by vorlov** [comment]
@maxhudson any luck on fixing this?

**Comment by maxhudson** [comment]
@vorlov no but I'll take another pass at it today!

**Comment by maxhudson** [comment]
@vorlov It's possible I'm misunderstanding you, but your issue may be that you're not using state to re-run the render method.

Please see this new example of how you should be updating the table's content: https://henrybuilt.github.io/react-sticky-table/#changing-content-example

Also, this may be useful: https://github.com/henrybuilt/react-sticky-table/blob/gh-pages/src/examples/ChangingContent/index.js

**Comment by maxhudson** [comment]
I'm guessing you're just changing the content of an individual `Row` which isn't resulting in the `StickyTable` re-rendering, and therefore not resulting in the cells resizing.

I will update the examples to make it obvious that the best practice is to make an array of rows and pass that to the `StickyTable`

**Comment by maxhudson** [comment]
@vorlov If that doesn't solve your issue, please provide more details for reproducing. It may be a browser-support issue.

**Comment by vorlov** [comment]
I guess I am doing something wrong, I just added drag and drop to your table and when I reorder headers it does not rerender their width, can't figure out the problem. just made it as your example shows

**Comment by vorlov** [comment]
Hi, this can be closed, I took your code from start, added DnD and now it works) thanks a lot for help)

**Comment by maxhudson** [comment]
@vorlov Great news. Glad you figured it out.
