### ISSUE TITLE
migrate to CSS-in-JS

### ISSUE THREAD

**Issue by horacioh** [henrybuilt/react-sticky-table#62]
is there any interest in migrating this package to use a CSS-in-JS technology like `styled-components` or `emotion`?

I understand that the use of pseudo-selectors is what makes it complex to use a technology like this without increasing the bundlesize, but I think it will be a lot cleaner for the codebase and maybe we can maintain the performance.

I can help with the migration, I'm using it for a client in a Typescript codebase and I think it would be useful since the package is not that big.

let me know!

**Comment by maxhudson** [comment]
@horacioh It's possible I don't understand CSS-in-JS well-enough, but my understanding is it's closer to using inline styles (like `<div style="">`) than actual css and you lose a lot of the benefits of CSS (Ability to specify pseudo-selectors, ability for people to opt out of styles by not including the stylesheet, etc). I can do some more research, or you can pitch it in a bit more detail, but more skeptical about that.

**Comment by horacioh** [comment]
actually it's more powerfull now, you can do everything with it but it adds a little more JS to create the styles. I can create a PR within my fork so you can have a sense on how this will change

**Comment by maxhudson** [comment]
Go for it!

**Comment by sibelius** [comment]
anybody working on this?

**Comment by sibelius** [comment]
```jsx
import React from 'react';

import Table from './Table';
import styled from 'styled-components';

export const Row = styled.div`
  display: table-row;
`;

export const Cell = styled.div`
  display: table-cell;
  box-sizing: border-box;
`;

const WrapperTable = styled.div<Props>`
  position: relative;
  overflow: auto;
  height: 100%;
  box-sizing: border-box; 
  & ${Row}:nth-child(-n+${props => props.stickyHeaderCount}) ${Cell} {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 2;
  }
  & ${Row} ${Cell}:nth-child(-n+${props => props.stickyColumnCount}) {
    position: -webkit-sticky;
    position: sticky;
    left: 0;
    z-index: 2;
  }
  & ${Row}:nth-child(-n+${props => props.stickyHeaderCount}) ${Cell}:nth-child(-n+${props => props.stickyColumnCount}) {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    left: 0;
    z-index: 3;
  }
`;

/**
 * StickyTable Component
 * Responsive, dynamically sized fixed headers and columns for tables
 * ------------------------------------------------------------------
 * Intentionally not setting state because we don't want to require
 * a full re-render every time the user scrolls or changes the
 * width of a cell.
 */
type Props = {
  stickyHeaderCount: number,
  stickyColumnCount: number,
  children: React.ReactNode,
};
const StickyTable = (props: Props) => {
  /**
   * Get the column and header to render
   * @returns {undefined}
   */
  const stickyColumnCount = Math.min(props.stickyColumnCount || 1, 1);
  const stickyHeaderCount = Math.min(props.stickyHeaderCount || 1, 1);

  return (
    <WrapperTable
      stickyColumnCount={stickyColumnCount}
      stickyHeaderCount={stickyHeaderCount}
    >
      <Table>
        {props.children}
      </Table>
    </WrapperTable>
  );
};

export default StickyTable;
```

simpler and no css names conflicts

**Comment by sibelius** [comment]
@maxhudson let me know what you think about this implementation using styled-components

**Comment by horacioh** [comment]
@sibelius thanks for this! I think this implementation is a good start!, and is pretty similar to what I implement in #72 ;)

I will close that PR for now tho, because there are a ton of things I changed that are breaking changes, and I want to make sure I add a proper documentation for the migration,

this could be a good major version bump :)

**Comment by sibelius** [comment]
@horacioh can we have 3 implementations?

- pure css
- styled-components
- emotion

what do you think  @maxhudson?

**Comment by horacioh** [comment]
@sibelius how do you think it would be exported all three implementations?

sounds like a good idea but dunno if its going to complicate the library support?

**Comment by sibelius** [comment]
```jsx
import from 'react-sticky-table' // css
import from 'react-sticky-table/styled' // styled
import from 'react-sticky-table/emotion' // emotion
````

**Comment by maxhudson** [comment]
@sibelius I see your styled implementation - where are the supporting files for the other two implementations? Or are you thinking supporting multiple would make it easy for someone else who wants to apply their own styles using `styled`, `css` or `emotion`, and we're only using `styled` for the standard styles?

**Comment by horacioh** [comment]
I think the way styles are implemented is not something concerned to the component user?

I see the benefit on having a plain css implementation, but having emotion and styled components separate seems to me a little odd.

I'm not against any of these, I'm just having an honest not-that-informed opinion from someone who wants to help woth this library :)

cc @maxhudson @sibelius

**Comment by maxhudson** [comment]
@horacioh what you're saying makes sense to me

**Comment by horacioh** [comment]
hello hello!!

anything else I can do to merge this PR?
cc @sibelius @maxhudson

**Comment by maxhudson** [comment]
@horacioh Do you have a fork that hasn't had a pull requested yet? I only see one PR about onScroll

**Comment by horacioh** [comment]
oups!!!
yeah I did close it to change it to styled components....

my bad!!

**Comment by horacioh** [comment]
@maxhudson here it is! #73 ;)
