### ISSUE TITLE
multiple sticky rows/columns

### ISSUE THREAD

**Issue by adussarps** [henrybuilt/react-sticky-table#63]
Hi guys,
  Before forking the project, to implement this I prefer to ask if this not already done somewhere! I understood that it was implemented in version 2, but in v3 it does't seem to be possible to have multiple sticky columns isn't it?

**Comment by maxhudson** [comment]
Not yet but this is the #1 next feature we want to re-implement. If you do successfully implement, please let us know/create a PR!

**Comment by adussarps** [comment]
I did implemented it; I append dynamically new classes for the other columns that have to be sticky, not sure if it is the most elegant solution.
Another way would be to fit the n sticky columns into one sticky cell.

https://github.com/artefactory/react-sticky-table/blob/master/src/index.js

Here is my implementation, I'll fix the tests and clean it if you think it's the right way to go.

**Comment by maxhudson** [comment]
@adussarps I think this works for static content, but unfortunately it doesn't work for dynamically changing content as far as I can tell (see dynamic cell sizes and changing content examples here: https://henrybuilt.github.io/react-sticky-table/#resizing-cells-example). The additional sticky columns will need to keep their dynamic widths up to date with content in our package - not sure how to do that unfortunately.

**Comment by adussarps** [comment]
Yes, you are right indeed. A way to go would be to stick the first n columns into one sticky container then. This means each row would format it's child cells, I don't know about the performances of such a solution.

**Comment by maxhudson** [comment]
@adussarps Unfortunately I considered that and it's problematic because then they're out of flow with the other columns in the table and the heights are no longer dynamic. Best solution is probably to check for cell size changes using setInterval (because there's no reliable `on('resize')` event), and then update the sticky column offsets based on those. Probably decently performant, just takes some time to implement, and I have no time :(

**Comment by yuliaripple** [comment]
Hello! I would only want to refresh the question about several fixed columns. It would be very useful to implement this. Could you please answer, do you have some ideas how to resolve this? Do you plan to start to do this?

**Comment by maxhudson** [comment]
@yuliaripple It'd be a large chunk of work. I'll think about if it can be fit in, but it'd be great if someone else (you??) implemented a rough PR to get the ball rolling.

The first trick is deciding whether to support dynamic or only fixed widths. Probably should be dynamic for ease-of-use and it's not that much less performant. It could be passed a "fixed" prop or something to optimize for performance when column/row sizes are fixed.

The general approach for dynamic:

### styles
- styles have to have access to state
- state should store a width/height for each column/row
- each column should have an offset top/left value of net-height/net-width of lower-index columns (this gets inverted for right column/footer) - **this will be the most math-heavy/finicky part**

### the resize event
- listening to `resize` events doesn't work reliably, so we have to poll with setInterval
- in setInterval, check if first cell in each column/row has changed in width/height - **this will be the most performance-sensitive code**
- if it has changed, update state with new size - **this will be the easiest place to miss a css condition like box-sizing - we'd want to require `box-sizing`: `border-box`.**

**Comment by maxhudson** [comment]
https://github.com/henrybuilt/react-sticky-table/pull/88
