### ISSUE TITLE
onScroll prop is never used

### ISSUE THREAD

**Issue by mgramigna** [henrybuilt/react-sticky-table#65]
The README states how the `StickyTable` component takes an `onScroll` function as a prop that gets called with an object, seen [here](https://github.com/henrybuilt/react-sticky-table#events)

On the most recent version of `react-sticky-table`, this `onScroll` handler never gets called. Was this intentional? If not, could this be added back? I have added some code to do it on a forked copy of this repository. If you want to take a look, you can find the diff [here](https://github.com/henrybuilt/react-sticky-table/compare/master...mgramigna:utilize-onscroll-prop)

**Comment by maxhudson** [comment]
I meant to remove that, but we'll add it back!

**Comment by maxhudson** [comment]
Closing as you should now be able to pass any prop, including `onScroll` to the scroll wrapper
