### ISSUE TITLE
how to properly show "no data" row?)

### ISSUE THREAD

**Issue by vorlov** [henrybuilt/react-sticky-table#7]
if we have 0 rows we need to show no data row

**Comment by maxhudson** [comment]
@vorlov There is currently no package-specific support for this, but you can create your own row that looks like this: `<Row><Cell>No data</Cell></Row>`. I'd recommend disabling the sticky column when there is no data if you use this approach.

The alternative method I'd suggest is hiding the table and displaying some No Data message in it's place.

**Comment by vorlov** [comment]
thanks, it helped
