### ISSUE TITLE
the header of table cover the dropdown list

### ISSUE THREAD

**Issue by twk7890** [henrybuilt/react-sticky-table#83]
similar issues on https://github.com/mbrn/material-table/issues/416
hard to add the style z-index to control the style of header style
![image](https://user-images.githubusercontent.com/27971797/55528358-23dd4c00-5662-11e9-9de3-f3f7d5591189.png)

**Comment by maxhudson** [comment]
@twk7890 I see what you mean - will investigate!

**Comment by Thebigbignooby** [comment]
what's the status on this ?

**Comment by maxhudson** [comment]
Will try to get to it this weekend, but am super busy. Happy to accept PR - should be a matter of accepting a `headerStyle` prop and applying it to the right element - but unclear if zIndex needs to be applied to cells or header row itself.

**Comment by maxhudson** [comment]
https://github.com/henrybuilt/react-sticky-table/pull/84
