### ISSUE TITLE
Issues when having more than 1 sticky row/column

### ISSUE THREAD

**Issue by maeriens** [henrybuilt/react-sticky-table#90]
There are a few issues around having more than 1 sticky row or column - header or footer.

Here it can be seen that a header and a left colum works OK, but as soon as I add another left column, the last cell of the header (top right corner) and the first cells of the last rows are displayed (bottom left corner).
Didn't go much through it but it seems that `right: 0`/ `bottom: 0` gets added to them as if they were footer instead of header and right instead of left.

![tables](https://user-images.githubusercontent.com/5074186/81483223-e5c23c80-9212-11ea-8335-001094743675.gif)

Another issue I found is that when I have more than 2 stickies to the left, or 3 to the right, the calculations for the stickies get a little 'gap' between them where you an see what is scrolled behind.

![seethrough](https://user-images.githubusercontent.com/5074186/81483291-87e22480-9213-11ea-883e-d5a2194a6ae5.gif)

I found this when I added the knobs to see how n stickies would work locally - so decided to create a PR with all that in https://github.com/henrybuilt/react-sticky-table/pull/89

I will try to see if I have some bandwith to help with these issues - but wanted to have them documented anyway

**Comment by maeriens** [comment]
I have solved locally the 2nd issue - the problem was that it always calculated the `left`/`right` spacing adding the first/last `width` instead of the previous/next width.

**Comment by maeriens** [comment]
Done both in #91

**Comment by maxhudson** [comment]
resolved by #91
