### ISSUE TITLE
Does react-sticky-table work with <table> too ? 

### ISSUE THREAD

**Issue by stephyswe** [henrybuilt/react-sticky-table#97]
Hi, 

I've a react-table but is react-sticky-table also for `<table />` components? 
I believe I had a workable version afew weeks ago but not sure. 

If so, would it be possible to show an example using <table /> with react-table.

That be very helpful

Kind regards,
Stephanie Hallberg

**Comment by maxhudson** [comment]
I haven’t ever tried that, but can look into it a bit. I don’t believe
we’ve changed anything that would affect that though!

Can you provide your example as a start?

**Comment by maxhudson** [comment]
closed as dup of #96
